import Vue from 'vue'
import { Scrollbar, DatePicker, Divider, Backtop, MessageBox, Button, RadioGroup, TimelineItem, Timeline, Radio, Select, Option, Tag, Tree, Form, FormItem, Input, Message, Container, Dialog, Header, Pagination, Aside, Main, Menu, Submenu, MenuItem, Breadcrumb, BreadcrumbItem, Card, Row, Col, Table, Tooltip, TableColumn, Switch } from 'element-ui'

Vue.use(DatePicker)
Vue.use(Backtop)
Vue.use(Divider)
Vue.use(RadioGroup)
Vue.use(Scrollbar)
Vue.use(TimelineItem)
Vue.use(Timeline)
Vue.use(Button)
Vue.use(Radio)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Row)
Vue.use(Col)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Switch)
Vue.use(Tooltip)
Vue.use(Pagination)
Vue.use(Dialog)
Vue.use(Tag)
Vue.use(Tree)
Vue.use(Option)
Vue.use(Select)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
